[package]
name = "librs"
version.workspace = true
edition.workspace = true

[dependencies]
battery.workspace = true
cargo_metadata = "0.18.1"
chrono.workspace = true
clap.workspace = true
clap_complete.workspace = true
color-print.workspace = true
mp4ameta.workspace = true
platform-lp.workspace = true
pretty-duration.workspace = true
progressing.workspace = true
serde.workspace = true
terminal = { version = "0.2.1", features = ["crossterm-backend"] }
toml.workspace = true
walkdir.workspace = true
