[package]
name = "sysinfo"
version.workspace = true
edition.workspace = true

[dependencies]
battery.workspace = true
clap.workspace = true
clap_complete.workspace = true
librs.workspace = true
serde.workspace = true
serde_json.workspace = true
